version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - '80:3000' # ポートを3000から80に変更
    environment:
      - NODE_ENV=production # 環境をdevelopmentからproductionに変更
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - '80:8000' # ポートを8000から80に変更
    environment:
      - APP_ENV=production # 環境をdevelopmentからproductionに変更
      - DB_CONNECTION=${DB_CONNECTION} # 本番環境用のDB_CONNECTION
      - DB_HOST=${DB_HOST} # 本番環境用のDB_HOST
      - DB_PORT=${DB_PORT} # 本番環境用のDB_PORT
      - DB_DATABASE=${DB_DATABASE} # 本番環境用のデータベース名
      - DB_USERNAME=${DB_USERNAME} # 本番環境用のユーザー名
      - DB_PASSWORD=${DB_PASSWORD} # 本番環境用のパスワード


volumes:
  db_data:
