version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - '80:3000' # ポートを3000から80に変更
    environment:
      - NODE_ENV=production # 環境をdevelopmentからproductionに変更
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL} # 本番環境用のバックエンドURL
      - NEXT_PUBLIC_BACKEND_IMG_URL=${NEXT_PUBLIC_BACKEND_IMG_URL} # 本番環境用の画像取得URL
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - '80:8000' # ポートを8000から80に変更
    environment:
      - APP_DEBUG=false # デバッグモードをfalseに変更
      - APP_ENV=production # 環境をdevelopmentからproductionに変更
      - APP_URL=${APP_URL} # 本番環境用のAPP_URL
      - APP_KEY=${APP_KEY} # 本番環境用のAPP_KEY
      - APP_URL=${APP_URL} # 本番環境用のAPP_URL
      - APP_NAME=${APP_NAME} # 本番環境用のAPP_NAME
      - CACHE_DRIVER=${CACHE_DRIVER} # 本番環境用のCACHE_DRIVER
      - DB_CONNECTION=${DB_CONNECTION} # 本番環境用のDB_CONNECTION
      - DB_HOST=${DB_HOST} # 本番環境用のDB_HOST
      - DB_PORT=${DB_PORT} # 本番環境用のDB_PORT
      - DB_DATABASE=${DB_DATABASE} # 本番環境用のデータベース名
      - DB_USERNAME=${DB_USERNAME} # 本番環境用のユーザー名
      - DB_PASSWORD=${DB_PASSWORD} # 本番環境用のパスワード
      - FILESYSTEM_DISK=${FILESYSTEM_DISK} # 本番環境用のFILESYSTEM_DISK
      - FRONTEND_URL=${FRONTEND_URL} # 本番環境用のフロントエンドURL
      - JAWSDB_URL=${JAWSDB_URL} # 本番環境用のJAWSDB_URL
      - LOG_CHANNEL=${LOG_CHANNEL} # 本番環境用のLOG_CHANNEL
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL} # 本番環境用のLOG_DEPRECATIONS_CHANNEL
      - LOG_LEVEL=${LOG_LEVEL} # 本番環境用のLOG_LEVEL
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION} # 本番環境用のMAIL_ENCRYPTION
      - MAIL_FROM_NAME=${MAIL_FROM_NAME} # 本番環境用のMAIL_FROM_NAME
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS} # 本番環境用のMAIL_FROM_ADDRESS
      - MAIL_HOST=${MAIL_HOST} # 本番環境用のMAIL_HOST
      - MAIL_PASSWORD=${MAIL_PASSWORD} # 本番環境用のMAIL_PASSWORD
      - MAIL_PORT=${MAIL_PORT} # 本番環境用のMAIL_PORT
      - MAIL_USERNAME=${MAIL_USERNAME} # 本番環境用のMAIL_USERNAME
      - MANAGER_ROLE=${MANAGER_ROLE} # 本番環境用のMANAGER_ROLE
      - OWNER_ROLE=${OWNER_ROLE} # 本番環境用のOWNER_ROLE
      - STAFF_ROLE=${STAFF_ROLE} # 本番環境用のSTAFF_ROLE
      - REACT_APP_ENCRYPTION_KEY=${REACT_APP_ENCRYPTION_KEY} # 本番環境用のREACT_APP_ENCRYPTION_KEY
      - REACT_APP_MANAGER_ROLE=${REACT_APP_MANAGER_ROLE} # 本番環境用のREACT_APP_MANAGER_ROLE
      - REACT_APP_OWNER_ROLE=${REACT_APP_OWNER_ROLE} # 本番環境用のREACT_APP_OWNER_ROLE
      - REACT_APP_STAFF_ROLE=${REACT_APP_STAFF_ROLE} # 本番環境用のREACT_APP_STAFF_ROLE
      - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS} # 本番環境用のSANCTUM_STATEFUL_DOMAINS
      - SESSION_CONNECTION=${SESSION_CONNECTION} # 本番環境用のSESSION_CONNECTION
      - SESSION_DMAIN=${SESSION_DMAIN} # 本番環境用のSESSION_DMAIN
      - SESSION_LIFETIME=${SESSION_LIFETIME} # 本番環境用のSESSION_LIFETIME
      - SESSION_DRIVER=${SESSION_DRIVER} # 本番環境用のSESSION_DRIVER
      - SESSION_SECURE_KEY=${SESSION_SECURE_KEY} # 本番環境用のSESSION_SECURE_KEY
      



volumes:
  db_data:
